// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnm_HeIsVGISWqe6yp0P_8XFtpbu44gGo',
    appId: '1:879526655151:web:b0ed39e13c6d08647d905a',
    messagingSenderId: '879526655151',
    projectId: 'pomba-22bf9',
    authDomain: 'pomba-22bf9.firebaseapp.com',
    storageBucket: 'pomba-22bf9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Dg77v5Pqua82x4-ABcxTgOSBf11dS5k',
    appId: '1:879526655151:android:b079996ecd5023817d905a',
    messagingSenderId: '879526655151',
    projectId: 'pomba-22bf9',
    storageBucket: 'pomba-22bf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjsHuNqj6oTflxx-MUZWQcccdEgU-vaKI',
    appId: '1:879526655151:ios:0bb2da2be78f57297d905a',
    messagingSenderId: '879526655151',
    projectId: 'pomba-22bf9',
    storageBucket: 'pomba-22bf9.firebasestorage.app',
    iosBundleId: 'com.example.pumbaEx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjsHuNqj6oTflxx-MUZWQcccdEgU-vaKI',
    appId: '1:879526655151:ios:0bb2da2be78f57297d905a',
    messagingSenderId: '879526655151',
    projectId: 'pomba-22bf9',
    storageBucket: 'pomba-22bf9.firebasestorage.app',
    iosBundleId: 'com.example.pumbaEx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnm_HeIsVGISWqe6yp0P_8XFtpbu44gGo',
    appId: '1:879526655151:web:750003780e410d167d905a',
    messagingSenderId: '879526655151',
    projectId: 'pomba-22bf9',
    authDomain: 'pomba-22bf9.firebaseapp.com',
    storageBucket: 'pomba-22bf9.firebasestorage.app',
  );
}
